/* RushEnd / Signal Cartography: reverse discovery turns an open hour into a calm nearby option. */
import { useMemo, useState } from "react";
import { ArrowRight, Clock3, LocateFixed, SlidersHorizontal } from "lucide-react";
import { Link } from "wouter";
import { useQueue } from "@/contexts/QueueContext";
import { crowdMeta } from "@/lib/queueData";

export default function DiscoverPage() {
  const { locations } = useQueue();
  const [from, setFrom] = useState("14:00");
  const [to, setTo] = useState("16:00");
  const [radius, setRadius] = useState("3");
  const ranked = useMemo(() => [...locations].sort((a, b) => a.wait - b.wait), [locations]);
  return <div className="page-in mx-auto max-w-[1280px] px-5 py-8 sm:px-10 lg:px-12 lg:py-12">
    <div className="grid gap-10 lg:grid-cols-[minmax(0,1fr)_330px]">
      <div><div className="flex items-center gap-2"><span className="eyebrow">Reverse discovery</span><span className="h-1 w-1 rounded-full bg-[#ff8a2b]" /></div><h1 className="mt-4 max-w-[620px] font-display text-[44px] font-semibold leading-[.98] tracking-[-.06em] sm:text-[60px]">Got an hour free? <span className="text-[#ffbd4a]">We'll fill it.</span></h1><p className="mt-5 max-w-[500px] text-[15px] leading-6 text-[#9daa9f]">Tell us your window. We'll show you what's quiet nearby.</p>
        <div className="mt-9 flex items-center gap-2 rounded-xl border border-[#a43dff]/20 bg-[#13202c] px-4 py-3 text-[12px] text-[#a9c4dc]"><LocateFixed size={15} className="text-[#a43dff]" /> Searching around your current location · India</div>
        <div className="mt-9 flex flex-wrap items-end gap-3 rounded-2xl border border-white/[.09] bg-[#1d111b] p-4"><div><label className="eyebrow" htmlFor="from">Free between</label><div className="mt-2 flex items-center gap-2 rounded-xl border border-white/[.12] bg-[#120c12] px-3 py-2.5"><Clock3 size={15} className="text-[#77877c]" /><input id="from" type="time" value={from} onChange={(event) => setFrom(event.target.value)} className="bg-transparent text-[13px] text-[#f3f3e8] outline-none" /><span className="text-[#66746a]">to</span><input type="time" value={to} onChange={(event) => setTo(event.target.value)} className="bg-transparent text-[13px] text-[#f3f3e8] outline-none" /></div></div><div><label className="eyebrow" htmlFor="radius">Radius</label><div className="mt-2 flex items-center gap-2 rounded-xl border border-white/[.12] bg-[#120c12] px-3 py-2.5"><SlidersHorizontal size={14} className="text-[#77877c]" /><select id="radius" value={radius} onChange={(event) => setRadius(event.target.value)} className="bg-transparent text-[13px] text-[#f3f3e8] outline-none"><option value="1" className="bg-[#1d111b]">1 km</option><option value="3" className="bg-[#1d111b]">3 km</option><option value="5" className="bg-[#1d111b]">5 km</option><option value="10" className="bg-[#1d111b]">10 km</option></select></div></div><button className="h-[42px] rounded-xl bg-[#f3f3e8] px-4 text-[12px] font-semibold text-[#0d090f] transition hover:bg-[#dce9df] active:scale-[.97]">Find my hour</button></div>
        <div className="mt-10 flex items-center justify-between"><div><p className="eyebrow">Quiet nearby</p><p className="mt-1 text-[12px] text-[#809086]">{ranked.length} places within {radius} km · ranked for {from}–{to}</p></div><span className="text-[11px] text-[#6f7e74]">Updated just now</span></div>
        <div className="mt-4 space-y-2">{ranked.map((location, index) => <Link key={location.id} href={`/location/${location.id}`} className="group flex w-full items-center gap-4 rounded-2xl border border-white/[.08] bg-[#1d111b] p-4 text-left transition hover:border-[#ff8a2b]/40 hover:bg-[#18211b]"><span className="metric w-5 text-[12px] text-[#617067]">0{index + 1}</span><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl border border-white/[.08] bg-[#120c12] text-[#829087]"><LocateFixed size={15} /></span><span className="min-w-0 flex-1"><span className="flex items-center gap-2"><span className="truncate text-[13px] font-semibold text-[#dde7de]">{location.name}</span><span className="h-1.5 w-1.5 shrink-0 rounded-full" style={{ background: crowdMeta[location.crowd].color }} /></span><span className="mt-1 block truncate text-[11px] text-[#7f8d82]">{location.category} · {location.note}</span></span><span className="text-right"><span className="metric block text-[18px] font-semibold" style={{ color: crowdMeta[location.crowd].color }}>{location.wait}m</span><span className="mt-1 block text-[10px] text-[#76847a]">{crowdMeta[location.crowd].label}</span></span><ArrowRight size={15} className="text-[#59675e] transition group-hover:translate-x-1 group-hover:text-[#a8c9b2]" /></Link>)}</div></div>
      <aside className="lg:sticky lg:top-[104px]"><div className="overflow-hidden rounded-2xl border border-white/[.09] bg-[#1d111b]"><div className="map-texture relative h-48"><svg viewBox="0 0 500 230" className="h-full w-full opacity-80"><path d="M-20 190 C90 150 160 180 260 90 S390 70 530 18" className="map-road major" /><path d="M30 0 C70 60 124 78 205 72 S310 150 470 170" className="map-road minor" /><path d="M228 0 C240 65 210 105 245 150 S270 205 265 245" className="map-road minor" /><circle cx="248" cy="112" r="5" fill="#a43dff" /><circle cx="248" cy="112" r="18" fill="none" stroke="#a43dff" opacity=".35" /></svg><div className="absolute left-4 top-4 rounded-full bg-[#0d090f]/75 px-2.5 py-1.5 text-[10px] text-[#9bb4c8] backdrop-blur">{radius} km radius</div></div><div className="p-5"><p className="eyebrow">Your free window</p><p className="metric mt-2 text-[32px] font-semibold text-[#f3f3e8]">{from} <span className="text-[15px] text-[#748178]">—</span> {to}</p><p className="mt-3 text-[12px] leading-5 text-[#8c9a8f]">The quietest option right now is <span className="font-medium text-[#c8d7ca]">{ranked[0]?.name}</span>. It is {ranked[0]?.wait} minutes from the front.</p><Link href="/" className="mt-5 flex items-center justify-center gap-2 rounded-xl border border-white/[.10] py-3 text-[12px] font-semibold text-[#c9d6cb] hover:bg-white/[.05]">Open map <ArrowRight size={14} /></Link></div></div></aside>
    </div>
  </div>;
}
