/* Queueless / Signal Cartography: historical behavior is drawn as a calm operating picture, not a spreadsheet. */
import { ArrowLeft, ArrowRight, CalendarDays, CheckCircle2, Clock3, Info, TrendingUp } from "lucide-react";
import { Link, useRoute } from "wouter";
import { useQueue } from "@/contexts/QueueContext";
import { crowdMeta } from "@/lib/queueData";

const hours = ["6a", "8a", "10a", "12p", "2p", "4p", "6p", "8p", "10p"];
const heat = [[1,1,2,2,3,2,1,1,0],[1,2,3,3,2,2,1,1,0],[2,3,3,2,2,1,1,0,0],[1,2,2,3,3,2,1,1,0],[1,1,2,3,2,2,1,0,0],[0,1,2,2,2,1,1,0,0],[0,0,1,1,1,1,0,0,0]];
const days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];

export default function LocationPage() {
  const [, params] = useRoute("/location/:id");
  const { locations } = useQueue();
  const location = locations.find((item) => item.id === params?.id) ?? locations[0];
  const meta = crowdMeta[location.crowd];
  return <div className="page-in mx-auto max-w-[1280px] px-5 py-8 sm:px-10 lg:px-12 lg:py-12"><Link href="/" className="inline-flex items-center gap-2 text-[11px] font-semibold text-[#839187] hover:text-[#dfe9df]"><ArrowLeft size={14} /> Back to the map</Link><div className="mt-7 flex flex-col justify-between gap-5 border-b border-white/[.09] pb-8 md:flex-row md:items-end"><div><div className="flex items-center gap-2"><span className="eyebrow">Location dashboard</span><span className="h-1 w-1 rounded-full bg-[#1d9e75]" /><span className="text-[11px] text-[#7c8b80]">{location.category}</span></div><h1 className="mt-3 font-display text-[40px] font-semibold leading-[1] tracking-[-.06em] sm:text-[55px]">How this place behaves, <span className="text-[#6ccca7]">over time.</span></h1><p className="mt-3 max-w-[520px] text-[14px] leading-6 text-[#98a59a]">Not just now — every day, mapped. {location.name} · {location.neighborhood.split(" · ")[0]}</p></div><div className="flex items-center gap-2 rounded-xl border border-[#1d9e75]/20 bg-[#1d9e75]/[.06] px-3.5 py-3 text-[11px] text-[#93d4b4]"><span className="h-1.5 w-1.5 rounded-full bg-[#1d9e75]" /> {location.confidence === "live" ? "Live signal" : "Pattern estimate"}</div></div>
    <div className="mt-8 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-white/[.08] bg-[#151d18] p-5"><p className="eyebrow">Quietest window</p><p className="mt-3 font-display text-[25px] font-semibold tracking-[-.04em] text-[#6ccca7]">8:00–9:30 AM</p><p className="mt-2 text-[11px] text-[#7d8b80]">Typically {Math.max(4, location.wait - 6)} min wait</p></div><div className="rounded-2xl border border-white/[.08] bg-[#151d18] p-5"><p className="eyebrow">Peak window</p><p className="mt-3 font-display text-[25px] font-semibold tracking-[-.04em] text-[#ed8864]">12:30–2:00 PM</p><p className="mt-2 text-[11px] text-[#7d8b80]">Typically {location.wait + 18} min wait</p></div><div className="rounded-2xl border border-white/[.08] bg-[#151d18] p-5"><p className="eyebrow">Prediction trust</p><p className="metric mt-3 text-[35px] font-semibold text-[#f3f3e8]">94<span className="text-[17px]">%</span></p><p className="mt-2 flex items-center gap-1.5 text-[11px] text-[#7d8b80]"><CheckCircle2 size={12} className="text-[#1d9e75]" /> accurate over 42 visits</p></div></div>
    <div className="mt-8 grid gap-8 lg:grid-cols-[minmax(0,1fr)_320px]"><div className="rounded-2xl border border-white/[.09] bg-[#151d18] p-5 sm:p-6"><div className="flex items-end justify-between"><div><p className="eyebrow">Hourly heatmap</p><p className="mt-2 text-[13px] text-[#a1aea2]">Average crowd intensity by day and time.</p></div><div className="flex items-center gap-2 text-[10px] text-[#77867b]"><span className="h-2 w-2 rounded-sm bg-[#1d9e75]" /> quiet <span className="h-2 w-2 rounded-sm bg-[#ba7517]" /> busy <span className="h-2 w-2 rounded-sm bg-[#d85a30]" /> peak</div></div><div className="mt-7 overflow-x-auto"><div className="min-w-[580px]"><div className="grid grid-cols-[40px_repeat(9,minmax(0,1fr))] gap-1.5">{hours.map((hour) => <span key={hour} className="text-center text-[9px] text-[#66746a]">{hour}</span>)}<span />{heat.flatMap((row, rowIndex) => <div key={`row-${rowIndex}`} className="contents"><span className="flex items-center text-[10px] text-[#77867b]">{days[rowIndex]}</span>{row.map((value, colIndex) => <div key={`${rowIndex}-${colIndex}`} title={`${days[rowIndex]} ${hours[colIndex]} · level ${value + 1}`} className="h-8 rounded-[5px] transition hover:scale-[1.04]" style={{ background: value === 0 ? "rgba(29,158,117,.18)" : value === 1 ? "rgba(29,158,117,.48)" : value === 2 ? "rgba(186,117,23,.66)" : "rgba(216,90,48,.78)" }} />)}</div>)}</div></div></div><div className="mt-7 flex items-center gap-3 rounded-xl border border-[#ba7517]/20 bg-[#ba7517]/[.06] px-4 py-3 text-[11px] leading-5 text-[#c8a36b]"><Info size={15} className="shrink-0 text-[#d59a46]" /> Tuesday lunch is the one to avoid. The pattern has held for the last three weeks.</div></div>
      <div className="space-y-3"><div className="rounded-2xl border border-white/[.09] bg-[#151d18] p-5"><div className="flex items-center justify-between"><div><p className="eyebrow">Recent trend</p><p className="mt-1 text-[12px] text-[#7f8d82]">Average wait, last 4 weeks</p></div><TrendingUp size={16} className="text-[#1d9e75]" /></div><div className="mt-5 flex h-28 items-end gap-2">{[20,24,18,30,28,22,15,21,18,12,17,10,14,9,11,8].map((value, index) => <div key={index} className="group relative flex-1 rounded-t bg-[#1d9e75]/55 transition hover:bg-[#6ccca7]" style={{ height: `${value * 3.1}px` }}><span className="absolute -top-5 left-1/2 hidden -translate-x-1/2 text-[9px] text-[#9ab6a2] group-hover:block">{value}m</span></div>)}</div><div className="mt-3 flex justify-between text-[10px] text-[#66756b]"><span>4 weeks ago</span><span>Now</span></div></div><div className="rounded-2xl border border-white/[.09] bg-[#151d18] p-5"><div className="flex items-center gap-2"><CalendarDays size={15} className="text-[#8c9c90]" /><p className="eyebrow">Signal notes</p></div><div className="mt-4 space-y-3 text-[11px] leading-5 text-[#89978d]"><p className="flex gap-2"><span className="mt-2 h-1 w-1 shrink-0 rounded-full bg-[#1d9e75]" /> Best for quick visits before 10 AM.</p><p className="flex gap-2"><span className="mt-2 h-1 w-1 shrink-0 rounded-full bg-[#ba7517]" /> Wednesday is the most consistent day.</p><p className="flex gap-2"><span className="mt-2 h-1 w-1 shrink-0 rounded-full bg-[#d85a30]" /> Festival dates can override this pattern.</p></div></div><Link href="/" className="flex items-center justify-center gap-2 rounded-xl border border-white/[.10] py-3 text-[11px] font-semibold text-[#b8c6b9] hover:bg-white/[.05]">Check current wait <ArrowRight size={14} /></Link></div></div>
  </div>;
}
