/* Vaqo / Signal Cartography: errands become an ordered route, with time saved as the headline metric. */
import { useMemo, useState } from "react";
import { ArrowRight, Check, Clock3, MapPin, Plus, Sparkles, Trash2 } from "lucide-react";
import { Link } from "wouter";
import { useQueue } from "@/contexts/QueueContext";
import { Button } from "@/components/ui/button";
import { crowdMeta, type QueueLocation } from "@/lib/queueData";
import { cn } from "@/lib/utils";

export default function PlanPage() {
  const { locations } = useQueue();
  const [stops, setStops] = useState<string[]>(["citycare-opd", "union-bank"]);
  const [routeBuilt, setRouteBuilt] = useState(false);
  const selected = useMemo(() => stops.map((id) => locations.find((location) => location.id === id)).filter(Boolean) as QueueLocation[], [locations, stops]);
  const remaining = locations.filter((location) => !stops.includes(location.id));
  const removeStop = (id: string) => setStops((current) => current.filter((stop) => stop !== id));
  return <div className="page-in relative mx-auto max-w-[1280px] overflow-hidden px-5 py-8 sm:px-10 lg:px-12 lg:py-12">
    <div className="contour-wash pointer-events-none absolute -right-28 -top-24 h-[420px] w-[560px] opacity-70" />
    <div className="pointer-events-none absolute right-[17%] top-[13%] hidden h-[180px] w-[300px] opacity-60 lg:block"><svg viewBox="0 0 300 180" className="h-full w-full"><path d="M-10 135 C75 90 112 130 168 62 S250 72 315 10" fill="none" stroke="#ff8a2b" strokeWidth="1.4" strokeDasharray="4 8" /><path d="M-15 160 C76 115 120 150 184 84 S253 90 318 35" fill="none" stroke="#b6cbbd" strokeOpacity=".18" /><circle cx="168" cy="62" r="4" fill="#ff8a2b" /><circle cx="168" cy="62" r="15" fill="none" stroke="#ff8a2b" strokeOpacity=".28" /></svg></div>
    <div className="relative z-10 grid gap-10 lg:grid-cols-[minmax(0,1fr)_360px] lg:items-start">
      <div>
        <div className="flex items-center gap-2"><span className="eyebrow">Plan my day</span><span className="h-1 w-1 rounded-full bg-[#ff8a2b]" /></div>
        <h1 className="mt-4 max-w-[620px] font-display text-[42px] font-semibold leading-[.98] tracking-[-.06em] sm:text-[58px]">Tell us your errands. <span className="text-[#ffbd4a]">We'll tell you the order.</span></h1>
        <p className="mt-5 max-w-[550px] text-[15px] leading-6 text-[#9daa9f]">Bank, hospital, ration shop — we'll sequence them by crowd and travel time so you're not standing around twice.</p>
        <div className="mt-9 flex items-center gap-3 rounded-xl border border-[#ff8a2b]/20 bg-[#ff8a2b]/[.06] px-4 py-3 text-[12px] text-[#a9cbb6]"><Sparkles size={15} className="text-[#ff8a2b]" /><span>Planning with live crowd signals from Bengaluru.</span></div>

        <div className="mt-10"><div className="mb-3 flex items-center justify-between"><p className="eyebrow">Your stops</p><span className="text-[11px] text-[#77857a]">{selected.length} added</span></div><div className="space-y-2">{selected.length === 0 && <div className="rounded-2xl border border-dashed border-white/[.15] p-7 text-center text-[13px] text-[#7e8d82]">Add a stop below to start your route.</div>}{selected.map((location, index) => <div key={location.id} className="group flex items-center gap-4 rounded-2xl border border-white/[.09] bg-[#1d111b] p-4 transition hover:border-white/[.18]"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-[#291329] font-display text-[13px] font-semibold text-[#ffbd4a]">{index + 1}</span><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><p className="truncate text-[14px] font-semibold text-[#e6eee6]">{location.name}</p><span className="h-1.5 w-1.5 rounded-full" style={{ background: crowdMeta[location.crowd].color }} /></div><p className="mt-1 text-[11px] text-[#7d8c81]">{location.category} · {location.neighborhood.split(" · ")[0]}</p></div><div className="hidden text-right sm:block"><p className="metric text-[16px] font-semibold" style={{ color: crowdMeta[location.crowd].color }}>{location.wait}m</p><p className="text-[10px] text-[#77867b]">right now</p></div><button onClick={() => removeStop(location.id)} aria-label={`Remove ${location.name}`} className="flex h-8 w-8 items-center justify-center rounded-lg text-[#67766b] opacity-0 transition hover:bg-[#ff5d73]/10 hover:text-[#ff6b73] group-hover:opacity-100 focus:opacity-100"><Trash2 size={14} /></button></div>)}</div></div>

        <div className="mt-9"><p className="eyebrow">Add a stop</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{remaining.slice(0, 4).map((location) => <button key={location.id} onClick={() => setStops((current) => [...current, location.id])} className="flex items-center gap-3 rounded-xl border border-white/[.08] bg-[#121914] px-3.5 py-3 text-left transition hover:border-[#ff8a2b]/40 hover:bg-[#18211b]"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-white/[.05] text-[#829289]"><MapPin size={15} /></span><span className="min-w-0 flex-1"><span className="block truncate text-[12px] font-medium text-[#d7e1d7]">{location.name}</span><span className="mt-1 block text-[10px] text-[#718075]">{location.category} · {location.wait}m wait</span></span><Plus size={14} className="text-[#659078]" /></button>)}</div></div>
        <div className="mt-8"><Button disabled={selected.length === 0} onClick={() => setRouteBuilt(true)} className="h-12 gap-2 rounded-xl bg-[#f3f3e8] px-5 text-[13px] font-semibold text-[#0d090f] hover:bg-[#dce9df] disabled:cursor-not-allowed disabled:opacity-40">Build my route <ArrowRight size={16} /></Button></div>
      </div>

      <div className="lg:sticky lg:top-[102px]">
        {routeBuilt ? <div className="overflow-hidden rounded-2xl border border-[#ff8a2b]/25 bg-[#1d111b]"><div className="relative h-36 overflow-hidden"><img src="/manus-storage/queueless-route-detail_a0e2c628.jpg" alt="A railway ticket counter queue" className="h-full w-full object-cover opacity-65" /><div className="absolute inset-0 bg-gradient-to-t from-[#1d111b] via-[#1d111b]/20 to-transparent" /><div className="absolute bottom-4 left-5"><p className="eyebrow text-[#9be3c4]">Your route</p><h2 className="mt-1 font-display text-[24px] font-semibold tracking-[-.05em]">Here's your day, minimized.</h2></div></div><div className="space-y-4 p-5"><div className="flex items-end justify-between border-b border-white/[.08] pb-4"><div><p className="eyebrow">Time saved</p><p className="metric mt-2 text-[37px] font-semibold text-[#ffbd4a]">42<span className="ml-1 text-[16px]">min</span></p></div><div className="text-right text-[11px] text-[#819086]">vs random order<br /><span className="text-[#b8c6ba]">2h 14m total</span></div></div><div className="space-y-0">{selected.map((location, index) => <div key={location.id} className="relative flex gap-3 pb-5 last:pb-0"><div className="flex flex-col items-center"><span className="relative z-10 flex h-6 w-6 items-center justify-center rounded-full border border-[#ff8a2b]/40 bg-[#172820] text-[10px] font-semibold text-[#ffbd4a]">{index + 1}</span>{index < selected.length - 1 && <span className="absolute top-6 h-full w-px bg-[#ff8a2b]/25" />}</div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><p className="text-[13px] font-semibold text-[#dfe8df]">{location.name}</p><span className="whitespace-nowrap text-[11px] text-[#87968b]">{index === 0 ? "Leave 9:10" : `Arrive 10:${index === 1 ? "05" : "35"}`}</span></div><p className="mt-1 flex items-center gap-1 text-[10px] text-[#7c8a80]"><Clock3 size={10} /> {location.wait}m predicted wait · {location.category}</p></div></div>)}</div><Link href="/" className="flex items-center justify-center gap-2 rounded-xl border border-white/[.10] py-3 text-[12px] font-semibold text-[#c8d4c9] transition hover:border-white/[.25] hover:bg-white/[.04]">View on map <ArrowRight size={14} /></Link></div></div> : <div className="rounded-2xl border border-white/[.09] bg-[#1d111b] p-5"><div className="flex h-40 items-center justify-center rounded-xl border border-dashed border-white/[.10] bg-[#120c12] text-center"><div><div className="mx-auto flex h-10 w-10 items-center justify-center rounded-full bg-[#291329] text-[#ffbd4a]"><RouteIcon /></div><p className="mt-3 text-[12px] font-medium text-[#cdd8ce]">Your route will show up here.</p><p className="mt-1 text-[11px] text-[#77867b]">Add 2 or more stops to compare the order.</p></div></div><div className="mt-5 flex items-start gap-3 text-[11px] leading-5 text-[#7c8b80]"><Check size={14} className="mt-0.5 shrink-0 text-[#ff8a2b]" /> We balance current queues, typical patterns, and travel time.</div></div>}
      </div>
    </div>
  </div>;
}

function RouteIcon() { return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7"><circle cx="6" cy="18" r="2.5" /><circle cx="18" cy="6" r="2.5" /><path d="M8.2 16.6c2.7-1.2 4.6-2.9 5.6-5.3.7-1.7 1.7-2.8 3.4-3.6" /></svg>; }
