/* Vaqo / Signal Cartography: personal activity makes a city signal feel reciprocal and useful. */
import { ArrowRight, Bookmark, Check, Clock3, MapPin, Settings2, Sparkles, TrendingDown, UserRound } from "lucide-react";
import { Link } from "wouter";
import { useQueue } from "@/contexts/QueueContext";
import { crowdMeta } from "@/lib/queueData";

const history = [
  { place: "CityCare OPD", meta: "Hospital · Old Town", when: "Today · 9:42 AM", wait: "11 min", tone: "teal" },
  { place: "Civic Seva Kendra", meta: "Government · Market Ward", when: "Yesterday · 10:15 AM", wait: "26 min", tone: "amber" },
  { place: "Union Bank · Central", meta: "Bank · Civic Square", when: "18 Aug · 3:30 PM", wait: "19 min", tone: "teal" },
];

export default function ProfilePage() {
  const { locations } = useQueue();
  const saved = locations.slice(0, 3);
  return <div className="page-in relative mx-auto max-w-[1280px] overflow-hidden px-5 py-8 sm:px-10 lg:px-12 lg:py-12"><div className="contour-wash pointer-events-none absolute -right-20 -top-20 h-[320px] w-[460px] opacity-60" /><div className="relative z-10 flex flex-col justify-between gap-5 border-b border-white/[.09] pb-8 sm:flex-row sm:items-end"><div className="flex items-center gap-4"><div className="flex h-16 w-16 items-center justify-center rounded-2xl border border-[#a43dff]/30 bg-[#13202c] font-display text-[22px] font-semibold text-[#a8cdf2]">AR</div><div><p className="eyebrow">My activity</p><h1 className="mt-2 font-display text-[36px] font-semibold tracking-[-.06em]">Hi, Ananya.</h1><p className="mt-1 text-[12px] text-[#7c8b80]">India · member since August</p></div></div><button className="flex items-center gap-2 rounded-xl border border-white/[.10] px-3.5 py-2.5 text-[11px] font-semibold text-[#acb9ad] hover:bg-white/[.05]"><Settings2 size={14} /> Preferences</button></div>
    <div className="mt-9 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-[#ff8a2b]/20 bg-[#1d111b] p-5"><div className="flex items-center gap-2 text-[#ffbd4a]"><TrendingDown size={16} /><span className="eyebrow text-[#84cfad]">Time not wasted</span></div><p className="metric mt-4 text-[35px] font-semibold text-[#f3f3e8]">2h 18m</p><p className="mt-1 text-[11px] text-[#7d8c82]">across your visits</p></div><div className="rounded-2xl border border-[#a43dff]/20 bg-[#1d111b] p-5"><div className="flex items-center gap-2 text-[#ff5cc8]"><Sparkles size={16} /><span className="eyebrow text-[#9abfec]">People helped</span></div><p className="metric mt-4 text-[35px] font-semibold text-[#f3f3e8]">12</p><p className="mt-1 text-[11px] text-[#7d8c82]">because you checked in</p></div><div className="rounded-2xl border border-[#ff9b18]/20 bg-[#1d111b] p-5"><div className="flex items-center gap-2 text-[#ffb52d]"><Check size={16} /><span className="eyebrow text-[#d5ac72]">Signal accuracy</span></div><p className="metric mt-4 text-[35px] font-semibold text-[#f3f3e8]">94<span className="text-[18px]">%</span></p><p className="mt-1 text-[11px] text-[#7d8c82]">your last 10 visits</p></div></div>
    <div className="mt-10 grid gap-10 lg:grid-cols-[minmax(0,1fr)_360px]"><div><div className="flex items-center justify-between"><div><p className="eyebrow">Check-in history</p><p className="mt-1 text-[12px] text-[#7d8b80]">Your small contributions to the map.</p></div><button className="text-[11px] font-semibold text-[#ffbd4a] hover:text-[#a5e5c6]">See all</button></div><div className="mt-4 space-y-2">{history.map((visit) => <div key={`${visit.place}-${visit.when}`} className="flex items-center gap-4 rounded-2xl border border-white/[.08] bg-[#1d111b] p-4"><span className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-xl ${visit.tone === "teal" ? "bg-[#ff8a2b]/10 text-[#ffbd4a]" : "bg-[#ff9b18]/10 text-[#ffb52d]"}`}><Check size={16} /></span><div className="min-w-0 flex-1"><p className="truncate text-[13px] font-semibold text-[#dce6dd]">{visit.place}</p><p className="mt-1 text-[11px] text-[#7e8d82]">{visit.meta}</p></div><div className="text-right"><p className="metric text-[15px] font-semibold text-[#b8c8ba]">{visit.wait}</p><p className="mt-1 text-[10px] text-[#6d7b71]">{visit.when}</p></div></div>)}</div></div><div><div className="flex items-center justify-between"><div><p className="eyebrow">Saved places</p><p className="mt-1 text-[12px] text-[#7d8b80]">Quick-glance status.</p></div><Bookmark size={15} className="text-[#78877d]" /></div><div className="mt-4 space-y-2">{saved.map((location) => <Link key={location.id} href={`/location/${location.id}`} className="group flex w-full items-center gap-3 rounded-2xl border border-white/[.08] bg-[#1d111b] p-3.5 text-left hover:border-white/[.18]"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#120c12] text-[#75847a]"><MapPin size={14} /></span><span className="min-w-0 flex-1"><span className="block truncate text-[12px] font-semibold text-[#dce6dd]">{location.name}</span><span className="mt-1 flex items-center gap-1.5 text-[10px] text-[#77867b]"><i className="h-1.5 w-1.5 rounded-full" style={{ background: crowdMeta[location.crowd].color }} />{crowdMeta[location.crowd].label}</span></span><span className="metric text-[15px] font-semibold" style={{ color: crowdMeta[location.crowd].color }}>{location.wait}m</span><ArrowRight size={13} className="text-[#59675e] transition group-hover:translate-x-1" /></Link>)}</div><Link href="/" className="mt-4 flex items-center justify-center gap-2 rounded-xl border border-white/[.10] py-3 text-[11px] font-semibold text-[#aebcaf] hover:bg-white/[.04]">Find another place <ArrowRight size={13} /></Link></div></div>
  </div>;
}
